namespace: flux-system
resources:
  - release-crd.yaml
  - operator-account.yaml
  - operator-deployment.yaml
secretGenerator:
  - name: helm-repositories
    files:
      - repositories.yaml
patchesStrategicMerge:
  - patch.yaml