namespace: flux-system
bases:
 - github.com/fluxcd/helm-operator/tree/helm-v3//deploy
secretGenerator:
  - name: helm-repositories
    files:
      - repositories.yaml
patchesStrategicMerge:
  - patch.yaml
